# Generated by Django 4.1.1 on 2022-10-19 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("functional_maintainers", "0001_initial"),
        ("technology", "0001_initial"),
        ("technical_maintainers", "0001_initial"),
        ("dependencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralInfo",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=150, unique=True)),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True,
                        to="dependencies.dependencies",
                        verbose_name="dependency_apps",
                    ),
                ),
                (
                    "functional_maintainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="functional_maintainers.functionalmaintainers",
                    ),
                ),
                (
                    "technical_maintainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="technical_maintainers.technicalmaintainers",
                    ),
                ),
                (
                    "technology",
                    models.ManyToManyField(
                        blank=True,
                        to="technology.technologies",
                        verbose_name="tech_apps",
                    ),
                ),
            ],
            options={
                "db_table": "general_info",
            },
        ),
    ]
