export const DEFAULT = 'DEFAULT' // THIS IS FOR SETUP PURPOSES, DELETE WHENEVER

/**
 * APPS TYPES 
 * */
export const POST_APP = 'POST_APP';
export const POST_APP_SUCCESS = 'POST_APP_SUCCESS';
export const POST_APP_FAILURE = 'POST_APP_FAILURE';
export const UPDATE_APP = 'UPDATE_APP';
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS';
export const UPDATE_APP_FAILURE = 'UPDATE_APP_FAILURE';
export const FETCH_APPS = 'FETCH_APPS';
export const FETCH_APPS_SUCCESS = 'FETCH_APPS_SUCCESS';
export const FETCH_APPS_FAILURE = 'FETCH_APPS_FAILURE';
export const FETCH_TECHNICAL_MAINTAINER = 'FETCH_TECHNICAL_MAINTAINER';
export const FETCH_TECHNICAL_MAINTAINER_SUCCESS = 'FETCH_TECHNICAL_MAINTAINER_SUCCESS';
export const FETCH_TECHNICAL_MAINTAINER_FAILURE = 'FETCH_TECHNICAL_MAINTAINER_FAILURE';
export const FETCH_FUNCTIONAL_MAINTAINER = 'FETCH_FUNCTIONAL_MAINTAINER';
export const FETCH_FUNCTIONAL_MAINTAINER_SUCCESS = 'FETCH_FUNCTIONAL_MAINTAINER_SUCCESS';
export const FETCH_FUNCTIONAL_MAINTAINER_FAILURE = 'FETCH_FUNCTIONAL_MAINTAINER_FAILURE';
export const FETCH_DEPENDENCIES = 'FETCH_DEPENDENCIES';
export const FETCH_DEPENDENCIES_SUCCESS = 'FETCH_DEPENDENCIES_SUCCESS';
export const FETCH_DEPENDENCIES_FAILURE = 'FETCH_DEPENDENCIES_FAILURE';
